name: Build and Deploy

on: [push, pull_request]

jobs:
  job1:
    environment:
      name: testing
    env:
      DATABASE_USERNAME=${{secrets.DATABASE_USERNAME}}
      DATABASE_PASSWORD=${{secrets.DATABASE_PASSWORD}}
      DATABASE_HOSTNAME=${{secrets.DATABASE_HOSTNAME}}
      DATABASE_PORT=${{secrets.DATABASE_PORT}}
      DATABASE_NAME=${{secrets.DATABASE_NAME}}
      SECRET_KEY=${{secrets.SECRET_KEY}}
      ALGORITHM=${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRY=${{secrets.ACCESS_TOKEN_EXPIRY}}
    runs-on: ubuntu-latest
    steps:
      - name: Pulling Git Repo
        uses: actions/checkout@v4
      - name: Installing python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Installing Dependencies.
        run: pip install -r requirements.txt
      - name: Installing & Running pytests
        run: |
          pip install pytest
          pytest